# try:
#     numerator = 10
#     denominater = 0

#     result = numerator/denominator


#     print(result)
# except:
#     print("Error:dominator cannot be 0.")


# try:
#     print(x)
# except:
#     print("An exeption occured")

# try:
#     print("hello")
# except:
#     print("somthing went wrong")
# else:
#     print("nothing went wrong")

try:
    print("hello")
except:
    print("somthing went wrong")
finally:
    print("the 'try except' is finished")